### ISSUE TITLE
Tiling process for panel validation

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/TNBC_python_scripts#15]
**Relevant background**

Addresses #10, part 1 (panel validation). For specific FOVs, we will need to stitch their channel images together for the upcoming paper.

**Design overview**

The final output of the tiled image for a FOV should resemble the output done by the image stitching process already done in `toffy` without . In other words, each channel will be displayed in a grid where the dimensions are dynamically computed by the function.

A few changes will need to be made:

1. The images should not ever need to be tiled in their original shape, which also means specifically checking for TMA-named folders should not be needed.
2. Padding should be added around each channel image.
3. Each channel should be normalized to be within the same dynamic range. Otherwise, certain images will come out much brighter/dimmer than others.

**Code mockup**

Two functions will be defined:

_generate_panel_validation_images_

Signature: `def generate_panel_validation_images(data_dir: pathlib.Path, img_sub_folder: str = "", fovs: Optional[List[str]] = None, padding: float=10)`

(INPUT NEEDED) this currently assumes that each FOV needing validation is contained in the same folder. If this will not always be the case, we should remove support for `data_dir` and `img_sub_folder` and instead have a generic `fov_paths` variable.

This function will iterate over each FOV, load the data in using `alpineer`, and pass it off to a helper function `create_stitched_fov_panel_image` with the specified `padding`. The helper function will return the complete stitched image which `generate_panel_validation_images` will then save (truncated to save space, if needed).

_create_stitched_fov_panel_image_

Signature: `def create_stitched_fov_panel_image(img_xr: xr.DataArray, padding: float=10)`

This function will take a lot of inspiration from `toffy.image_stitching.stitch_images`. However, due to the need to add padding and dynamic range normalization, we can't simply punt the process to this external stitching function.

- **Padding**
  - When defining the dimensions of the stitched image, we will need to account for the additional amount of padding required across both the row and column axis. If the image grid is a x b, and each image has dimensions m x n, then the new stitched dimensions will be: (a * m + (a + 1) * padding, b * n + (b + 1) * padding).
  - (INPUT NEEDED) because each channel images tend to have dark backgrounds, it will be most helpful to start with a completely white slate, as opposed to black.
  - Indexing will need to add the correct padding offset for image placement. Given the position of the image relative to the grid dimensions, we can simply multiply the respective row/column by the padding size to get the offset.
- **Dynamic range normalization**:
  - This can be accomplished by: `(img_vals - img.min()) / (img.max() - img.min())`
  - We should still keep division by 200 and size scaling to 0.25, this will make the images compatible with photoshop.

As mentioned in the design section, we will otherwise assume this function will duplicate the functionality of `stitch_images` without the need to tile anything to their original shape.

**Required inputs**

The user should provide a list of FOVs to generate tiled images for in their folder.

**Output files**

The tiled images will be outputted to a separate folder, called `panel_validation_tiles`, as `.tiffs` and using their corresponding FOV names.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [X] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

12/15

Estimated date when the finalized project will be merged in: 

Before Winter Closure.

**Comment by alex-l-kong** [comment]
@ngreenwald lmk if this captures the idea of what you were thinking about for with panel validation.

@srivarra @camisowers feel free to add on, especially for the INPUT NEEDED sections (there are two).

**Comment by ngreenwald** [comment]
Looks good. I would say it's simplest if the function just works on a single FOV at a time, no need to support a list of FOVs. 

I would say min-max normalization often doesn't lead to great results for MIBI data, I would consider 99% or something else. Can experiment with a couple and see what looks best. 

Candace has some example code you can take a look at.

**Comment by srivarra** [comment]
@alex-l-kong 

Looks pretty good to me, I really like the single `fov_paths` argument.

> (INPUT NEEDED) this currently assumes that each FOV needing validation is contained in the same folder. If this will not always be the case, we should remove support for data_dir and img_sub_folder and instead have a generic fov_paths variable.

Yeah I think this is a good idea. Is `fov_paths` a directory containing the fovs or the fov folder itself? Or you could create a wrapper function which loops over all fovs.

> (INPUT NEEDED) because each channel images tend to have dark backgrounds, it will be most helpful to start with a completely white slate, as opposed to black.

that makes sense.

**Comment by camisowers** [comment]
Makes sense to me. The functionality here is a lot more straight forward than `toffy.image_stitching.stitch_images`. You can essentially just use `load_images_from_dir` instead of `load_images_from_tree`, do whatever padding and normalization needed, and then call `alpineer.data_utils.stitch_images`.
