### ISSUE TITLE
Add functional marker thresholding

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/TNBC_python_scripts#18]
**Is your feature request related to a problem? Please describe.**

Addresses second-to-last bullet point in #10. Adds a definition for `visualize_marker_thresholds`, a function to visualize various distributions of markers per cell population type with their corresponding threshold.

**Describe the solution you'd like**

Implementation is largely borrowed from `ark.phenotyping.post_cluster_utils.plot_hist_thresholds`. However, this function currently does not handle the case where multiple markers with different thresholds must be specified, so a few changes need to be made:

1. The `marker` and `threshold` parameter should be condensed into a `marker_threshold_info` `dict` param which maps each marker to their corresponding threshold. The user can then specify multiple markers and each marker can have its corresponding threshold visualized.
    1. (INPUT NEEDED) Can we safely assume that all markers have a corresponding `threshold`? `plot_hist_threshold` has support for `threshold=None`, which turns off drawing the vertical threshold line, but if this assumption can be made, `visualize_marker_thresholds` doesn't need to support `None` values for thresholding.
2. The figure dimensions will need to change. Because `plot_hist_threshold` is currently designed to only visualize one marker distribution per population at a time, only one column was needed. There will now need to be `len(marker_threshold_info)` columns in this figure, with column `i` corresponding to the marker at index `i` in `marker_threshold_info.keys()`.
    1. (INPUT NEEDED) if `marker_threshold_info` is significantly large, the figure can blow up. An alternative is to save separate figures for each marker within the same function. Any other suggestions appreciated.
3. An additional loop over each `marker` will need to enclose the current loop over `populations`.
4. The `threshold` is no longer constant, so it should be accessed via `marker_threshold_info[marker]`.

**Additional context**

@ngreenwald where do we want to display the screenshot(s) for showing how Mantis is used to identify these thresholds?

**Comment by alex-l-kong** [comment]
@ngreenwald @camisowers @srivarra  let me know how this looks, again would appreciate feedback on the INPUT NEEDED sections.

**Comment by ngreenwald** [comment]
Looks good. I think this will be more useful as a function that works on a single marker at a time. I agree that saving a separate figure for each marker makes sense. 

We won't want to show the same cell types for each marker. We can loop over each marker, specifying which cell types to draw the histogram for. I think the default should be a histogram with the expression all cell types, and then additional histograms based on the populations the user specifies.

**Comment by alex-l-kong** [comment]
@ngreenwald ok cool. Just to clarify, no matter whether the user specifies specific populations per marker, we should still save a set of histograms with the distribution of all the cell types per each marker? Then, if there are specific populations per marker specified, visualize additional histograms for that marker with just those populations?

**Comment by ngreenwald** [comment]
Yeah, each marker will generate a plot with the populations selected. For our purposes, I'll pick two populations per marker. So three plots for each; total, cell pop 1, and cell pop 2. These can be saved as a single .pdf. Then we'll combine the PDFs for each of the markers together into the final figure.

**Comment by srivarra** [comment]
@alex-l-kong 

> (INPUT NEEDED) Can we safely assume that all markers have a corresponding threshold? `plot_hist_threshold` has support for `threshold=None`, which turns off drawing the vertical threshold line, but if this assumption can be made, `visualize_marker_thresholds` doesn't need to support `None` values for thresholding.

I think it's save to assume that there is always some corresponding threshold, if the user doesn't provide one, is it easy to create the threshold for them automatically inferred by the data?

> (INPUT NEEDED) if `marker_threshold_info` is significantly large, the figure can blow up. An alternative is to save separate figures for each marker within the same function. Any other suggestions appreciated.

You can use [`GridSpec`](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/gridspec_and_subplots.html#sphx-glr-gallery-subplots-axes-and-figures-gridspec-and-subplots-py) to dynamically create figures consisting of several subplots. For example if `len(marker_threshold_info) == 27`, we could have 4 figures with $3 \times 2$ subfigures and a remaining figure with $1 \times 3$ subfigures

**Comment by alex-l-kong** [comment]
<img width="650" alt="Screenshot 2023-12-18 at 1 57 38 PM" src="https://github.com/angelolab/TNBC_python_scripts/assets/31424707/cddeb972-4d6f-4624-98dd-02dc42e310dc">

@ngreenwald were you thinking something along these lines for a single marker?

**Comment by ngreenwald** [comment]
Yes exactly. If not in there already, we'll want the ability to set the x range and x/y dimensions of the figure
