### ISSUE TITLE
Cell Clustering Plots

### ISSUE THREAD

**Issue by camisowers** [angelolab/TNBC_python_scripts#19]
We need to create plots for:
1. number of cells per cluster
2. number of cells per fov
3. colored cell cluster masks from random subset of 20 FOVs 
4. cell type composition by tissue location of met
5. Flowchart showing all three levels of cell clustering

It's super quick to tweak and then reproduce these plots so if you have any preferences just lmk. I've displayed the data a couple ways so whichever one you think is best, or if you had something else in mind I can generate it.

Example plots:
1.
<img width="350" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/01fe2928-c879-437d-8e3b-1125f5e87aec">   <img width="350" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/aacee156-9432-40db-ac07-73e4aee41961">
2.
<img width="350" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/b4d2d258-49ec-4854-a1f4-5a1e66a3e85e">
<img width="350" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/bec22a82-ed6a-44ca-9b1b-cc6973ca68f4">
<img width="350" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/46b9bd63-ea94-4f12-983d-6937298df865">

4. 
<img width="650" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/38049893/ffc9f97e-6b10-4499-853b-e08cf52ddea1">

5. Will be higher resolution once I get biorender premium 🙃
![cell_cluster_hierarchy](https://github.com/angelolab/TNBC_python_scripts/assets/38049893/c3d739d7-751a-472e-ab21-b9c93a7e5592)

**Comment by ngreenwald** [comment]
1: looks good, let's do vertical bars. Will you plot them in this order? 
<img width="111" alt="image" src="https://github.com/angelolab/TNBC_python_scripts/assets/13770365/3baa1cf5-45fd-4d92-a7d5-4dc4fffebc8e">

Cancer I = cancer, cancer 2 = cancer EMT, cancer 3 = cancer other. 

Then put other and immune other at the end

2: The histogram looks good for cell counts. 

4: Looks good, can use same colormap for 3. 

5: Looks good. Can you change the meta cluster column so each cell type is in its own box? Then it will look the same as the merges that happen from cell cluster to broad.
