### ISSUE TITLE
Add tiling process for images before and after normalization

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/TNBC_python_scripts#22]
**Is your feature request related to a problem? Please describe.**

For specific channels in a run, we'll need to display a tiled image in acquisition order before and after normalization.

**Describe the solution you'd like**

Acquisition order is defined by the FOV number. It's assumed that there are no more -scan-2 images in a run.

There are two options that can be implemented

1. Visualize the before and after in separate images, and combine afterwards
2. Visualize the before and after in the same image

In case 1, we can use a process similar to #17 (and I'll likely export shared functionality to a separate function). Annotation will be the FOV number instead of the channel name. Padding will work the same.

Case 2 will be very similar to case 1, except there will need to be ample border space separating the before and after tiles. Indexing will need to take this into account when adding the after normalization images, since those will be to the right of the before normalization images.

(INPUT NEEDED) let me know which option works best.

**Comment by alex-l-kong** [comment]
@srivarra @camisowers @ngreenwald let me know how this looks. I'm debating between two display options right now, vote for which one you like more (or suggest a different option).

**Comment by ngreenwald** [comment]
Let's do 1 for now since it'll be simpler, and I think it will be easier to compare them that way.
